app/__init__.py
from flask import Flask

import mysql.connector 


# db = list()
db = mysql.connector.connect( # LLAMAMOS AL FUNCION CONNECT PARA CONECTARNOS
    host ='informatica.iesquevedo.es',
    port = 3333,
    ssl_disabled = True,
    user ='root', #USUARIO QUE USAMOS NOSOTROS
    password ='1asir', #CONTRASEÑA CON LA QUE NOS CONECTAMOS
    database='testFlask'
) 



def create_app():
    app = Flask(__name__)
    app.debug = True
    

    

    from .routes import routes
    from .routes import routes_jugadores
    
    app.register_blueprint(routes.rutas_coches)
    app.register_blueprint(routes_jugadores.rutas_jugadores)


    return app

app/routes/routes.py
import random
from flask import Flask, Blueprint, render_template, request, redirect, url_for

from app import db
from app.data.equipo_dao import EquipoDao
from app.data.modelo.equipo import Equipo


rutas_coches = Blueprint("routes", __name__)


@rutas_coches.route('/')
def index():
    return render_template('index.html')

@rutas_coches.route('/nueva')
def nueva():
    loquequiera=random.randint(1,100)
    loquequiera2=random.randint(1,100)


    return render_template('nueva.html',aleatorio1=loquequiera,aleatorio2=loquequiera2)



@rutas_coches.route('/verEquipos')
def verEquipos():
    equipo_dao = EquipoDao()
    nombre = request.args.get('nombre')
    equipos = equipo_dao.select_all(db)
    saludar = request.args.get('saludar')
   


    return render_template('test.html',equipos=equipos,saludar=saludar,nombre=nombre)




@rutas_coches.route('/addEquipo', methods=['POST'])   
def addEquipo():
    equipo_dao = EquipoDao()

    nombre = request.form['nombre']
    ciudad = request.form['ciudad']

    if (nombre == "" or ciudad == ""):
        return redirect(url_for('routes.verEquipos'))

    equipo_dao.insert(db,nombre,ciudad)
   
    #return render_template('ok.html')  
  
    return redirect(url_for('routes.verEquipos'))    

@rutas_coches.route('/delEquipo', methods=['POST'])   
def delEquipo():
    equipo_dao = EquipoDao()

    id = request.form['id']



    equipo_dao.delete(db,id)
   
    return redirect(url_for('routes.verEquipos'))    

@rutas_coches.route('/updateEquipo', methods=['POST'])   
def updateEquipo():
    equipo_dao = EquipoDao()

    id = request.form['id']
    nombre = request.form['nombre']
    ciudad = request.form['ciudad']

    if (ciudad == ""):
        equipo_dao.updateNombre(db,id,nombre)
    else:
        equipo_dao.update(db,id,nombre,ciudad)
   
    return redirect(url_for('routes.verEquipos'))    

app/routes/routes_jugadores.py
import random
from flask import Flask, Blueprint, render_template, request, redirect, url_for

from app import db
from app.data.jugadores_dao import JugadoresDao
from app.data.equipo_dao import EquipoDao
from app.data.modelo.equipo import Equipo


rutas_jugadores = Blueprint("routes_jugadores", __name__)


@rutas_jugadores.route('/delJugador', methods=['POST'])   
def delEquipo():
    id = request.form['id']
    equipo_dao = EquipoDao()
    equipo_dao.delete(db,id)
   
    return redirect(url_for('routes.verEquipos'))  



@rutas_jugadores.route('/verJugadores', methods=['POST','GET'])   
def verJugadores():
    jugadores = list()
    nombreEquipo = ""
    equipo_dao = EquipoDao()
    equipos = equipo_dao.select_all(db)
    

    if (request.method == 'POST'):
        id_equipo = request.form['id_equipo']
        jugadores_dao = JugadoresDao()
        jugadores = jugadores_dao.select_all(db,id_equipo)
        for equipo in equipos:
            
            if (id_equipo == str(equipo.id)):
               
                nombreEquipo  = equipo.nombre



    return render_template('jugadores.html',
                           jugadores=jugadores,
                           equipos=equipos,
                           nombreEquipo=nombreEquipo)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    {% block head %}
   
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
    <div id="content">{% block content %}contenido por defecto{% endblock %}</div>
    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/formulario.html
{% extends "base.html" %}
{% block title %}Formulario{% endblock %}


{% block content %}
    


  <form action=""  method="post">


  </form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}


{% block content %}
    <h1>CAMBIO NUEVO</h1>
    <p class="important">
      HOLA MUNDO
    </p>
    <a href="https://www.as.com">www.as.com</a>
    <a href="{{ url_for('static',filename='static.html') }}">estatico</a>
    <a href="{{ url_for('routes.verEquipos') }}">Test</a>
    
    <a href="{{ url_for('routes_jugadores.verJugadores') }}">jugadores</a>
{% endblock %}

{% block footer %}
FOOTER desde index asdas

asd asda sdasd 
{% endblock %}

app/templates/jugadores.html
{% extends "base.html" %}
{% block title %}Jugadores{% endblock %}


{% block content %}

<form action="/verJugadores"  method="post">
  <label
    for="id_equipo">EQUIPO</label>
    <select name="id_equipo" >
      {% for equipo in equipos %}
        <option value="{{equipo.id}}">{{equipo.nombre}}</option>
      {% endfor %}
    </select>
  <input type="submit" value="Ver" />
</form>

<br/>
<div style="align-content: center;" >
  <h1>{{nombreEquipo}}</h1>
</div>

{% if jugadores %}
<table border="1" style="width: 100%;">
  <tr><td>ID</td><td>NOMBRE</td><td>ID_EQUIPO</td></tr>
  {% for jugador in jugadores %}
      <tr>
        <td>{{ jugador.id }}</td> 
        <td>{{ jugador.nombre }}</td> 
        <td>{{ jugador.id_equipo }}</td>
      </tr>
     
  {% endfor %}
</table>

{% else %}
<h1>No hay jguadores</h1>

{% endif %}



{% endblock %}

app/templates/nueva.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>nueva</title>
   
</head>
<body>
    <div id="content">contenido de nueva
<br>


<a href="{{ url_for('routes.index') }}">Test</a>
{{aleatorio1}} + {{aleatorio2}} = {{aleatorio1 + aleatorio2}}
<img src="{{ url_for('static', filename='images/descarga.png') }}"/>

    </div>
    <div id="footer">
        
        FOOTER
        
    </div>
</body>
</html>

app/templates/ok.html
<html>
<body>

<h1>Se ha añadido</h1>


</body>

</html>

app/templates/test.html
{% extends "base.html" %}
{% block title %}Test{% endblock %}


{% block content %}
{% if error %}
<script>
  alert("{{error}}");
  </script>
{% endif %}
  {% if saludar == 'true' %}
    <h1>hola {{nombre}}</h1>
  {% endif %}
   <table border="1" style="width: 100%;">
    <tr><td>ID</td><td>NOMBRE</td><td>CIUDAD</td></tr>
    {% for equipo in equipos %}
       
          
        <tr>
          <td>{{ equipo.id }}</td> 
          <td>{{ equipo.nombre }}</td> 
          <td>{{ equipo.ciudad }}</td>
          <td><form action="/delEquipo"  method="post">
            <input type="hidden" name="id" value="{{equipo.id}}" />
            <input type="submit" value="Borrar" />
          </form></td>
          <td>otra columna</td>
        </tr>
       
    {% endfor %}
  </table>
<br/>
<div style="border: 1px;">
  <form action="/addEquipo"  method="post">
    <label
      for="nombre">Nombre</label>
    <input type="text" name="nombre" id="" value="" />
    <label
      for="ciudad">Ciudad</label>
    <input type="text" name="ciudad" value="" />
    <input type="submit" value="Add" />
  </form>
</div>

<br/>
<form action="/delEquipo"  method="post">
  <label
    for="nombre">ID</label>
    <select name="id" >
      {% for equipo in equipos %}
        <option value="{{equipo.id}}">{{equipo.nombre}}</option>
      {% endfor %}
    </select>
  <input type="submit" value="Borrar" />
</form>

<br/>
<form action="/updateEquipo"  method="post">
  <label
    for="nombre">ID</label>
  <select name="id" >
    {% for equipo in equipos %}
      <option value="{{equipo.id}}">{{equipo.nombre}}</option>
    {% endfor %}
  </select>

 
  <label
  for="nombre">Nombre</label>
<input type="text" name="nombre" id="" value="" />
<label
  for="ciudad">Ciudad</label>
<input type="text" name="ciudad" value="" />

  <input type="submit" value="update" />
</form>


{% endblock %}